services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment: # responsável por passar valores para o ambiente lá dentro do container
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5432:5432" # "host:guest"
